### ISSUE TITLE
Consider renaming the package

### ISSUE THREAD

**Issue by paluh** [jvliwanag/purescript-untagged-union#1]
First line of your README file is: "A data type for untagged unions." I think that `purescript-untagged` would be more descriptive name for this package ;-) Like in my previous comment - it is just a matter of preference for sure so just close the issue if you don't want to discuss naming issues.

**Comment by jvliwanag** [comment]
Still very open to renaming the project. And changing the name of everything else inside.

I initially named it as OneOf since my original idea was simply to use rowlist so it reads like:

```purescript
type ISB = OneOf (i :: Int, s :: String, b :: Boolean)
```

Incidentally, I found the same name used in: https://github.com/doolse/purescript-tscompat

Problem was it turns out, the labels in the rowlist aren't useful, and that the order matters. So I ended up with the current `|+|` operator.

So you're right, `untagged` as a name might be better, or perhaps `untagged-unions` to be more precise? If we choose the latter though, should we name our pacakge as `UntaggedUnions` or `Untagged.Unions`? Naming is hard 😢 

I'm also considering changing `|+|` to `|:` so it resembles typescript more.

**Comment by paluh** [comment]
I like `untagged-unions` :-) Maybe even `untagged-union` as it introduces single abstraction. I'm somehow trying to follow @natefaubion module naming suggestion:

* if a module introduces single abstract entity, a class or a type it can be called in singular

* If a module contains multiple instances or values of a given class / type I name it in plural form

Regarding operator I much prefer this one: `|+|` or maybe this `:+:` (I'm following similar convention `:*:` from `selda` in my ntuples module).

....naming is hard ;-)

**Comment by jvliwanag** [comment]
Finally did this in #10 :)
